export const Role = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
  LAB: "LAB",
  APPOINTMENT: "APPOINTMENT",
  CLINIC: "CLINIC",
  LAB_ASSISTANT: "LAB",
  APPOINTMENT_MANAGER: "APPOINTMENT",
  DISPENSARY_STAFF: "CLINIC",
  PATIENT: "PATIENT",
  RECEPTIONIST: "RECEPTIONIST",
  PHARMACY: "PHARMACY",
  NURSE: "NURSE",
  BILLING: "BILLING"
};
